// Kompaktes Mülltrennungs-Lexikon: gängige Alltagsgegenstände und wohin sie gehören.
// Kein Anspruch auf Vollständigkeit oder kommunale Sonderregeln — im Zweifel gilt
// immer die Auskunft des örtlichen Entsorgers.

export const LEXIKON = [
  { item: 'Bananenschale', bin: 'Biomüll' },
  { item: 'Kaffeesatz + Filtertüte', bin: 'Biomüll' },
  { item: 'Eierschalen', bin: 'Biomüll' },
  { item: 'Teebeutel', bin: 'Biomüll' },
  { item: 'Gekochte Essensreste', bin: 'Biomüll' },
  { item: 'Verschmutztes Papier (z.B. Pizzakarton mit Fettflecken)', bin: 'Restmüll' },
  { item: 'Windeln', bin: 'Restmüll' },
  { item: 'Kaugummi', bin: 'Restmüll' },
  { item: 'Zigarettenkippen', bin: 'Restmüll' },
  { item: 'Staubsaugerbeutel', bin: 'Restmüll' },
  { item: 'Asche (ausgekühlt)', bin: 'Restmüll' },
  { item: 'Kaputtes Geschirr/Porzellan', bin: 'Restmüll' },
  { item: 'Kassenbons (Thermopapier)', bin: 'Restmüll', hint: 'Nicht ins Altpapier, wegen Chemikalien' },
  { item: 'Fensterglas / Trinkgläser', bin: 'Restmüll', hint: 'Kein Verpackungsglas, gehört nicht in den Glascontainer' },
  { item: 'Zeitungen, Zeitschriften', bin: 'Papier' },
  { item: 'Kartons (sauber, gefaltet)', bin: 'Papier' },
  { item: 'Briefumschläge', bin: 'Papier' },
  { item: 'Prospekte', bin: 'Papier' },
  { item: 'Eierkarton', bin: 'Papier' },
  { item: 'Joghurtbecher', bin: 'Gelber Sack' },
  { item: 'Plastiktüten/-folien', bin: 'Gelber Sack' },
  { item: 'Konservendosen', bin: 'Gelber Sack' },
  { item: 'Getränkekartons (Tetra Pak)', bin: 'Gelber Sack' },
  { item: 'Styropor', bin: 'Gelber Sack' },
  { item: 'Verpackungen mit "Grüner Punkt"', bin: 'Gelber Sack' },
  { item: 'Zahnpastatube', bin: 'Gelber Sack' },
  { item: 'Glasflaschen (Verpackungsglas)', bin: 'Altglas-Container' },
  { item: 'Marmeladengläser', bin: 'Altglas-Container' },
  { item: 'Batterien', bin: 'Sondermüll', hint: 'Sammelbox im Supermarkt oder Wertstoffhof, nie in den Hausmüll' },
  { item: 'Energiesparlampen / LED-Lampen', bin: 'Sondermüll', hint: 'Enthalten teils Schadstoffe, Wertstoffhof/Recyclingstation' },
  { item: 'Farb-/Lackreste', bin: 'Sondermüll' },
  { item: 'Medikamente', bin: 'Sondermüll', hint: 'Apotheke oder Wertstoffhof' },
  { item: 'Altöl', bin: 'Sondermüll' },
  { item: 'Elektrogeräte (Handy, Ladekabel, Toaster)', bin: 'Elektroschrott', hint: 'Wertstoffhof oder Rücknahme im Handel' },
  { item: 'Alte Möbel', bin: 'Sperrmüll' },
  { item: 'Matratzen', bin: 'Sperrmüll' },
  { item: 'Teppiche', bin: 'Sperrmüll' },
  { item: 'Fahrräder (kaputt)', bin: 'Sperrmüll' },
  { item: 'Christbaum / Weihnachtsbaum', bin: 'Weihnachtsbaum' },
  { item: 'Gartenabfälle, Laub, Äste', bin: 'Biomüll', hint: 'Größere Mengen: Grünschnittsammlung/Recyclinghof' },
  { item: 'Alttextilien / Kleidung', bin: 'Altkleider-Container' },
  { item: 'Schuhe', bin: 'Altkleider-Container' },
  { item: 'Speiseöl/Fett', bin: 'Wertstoffhof', hint: 'Nicht ins Spülbecken oder den Biomüll' },
  { item: 'Bauschutt', bin: 'Wertstoffhof' },
  { item: 'Kork', bin: 'Restmüll' },
  { item: 'Kerzenreste', bin: 'Restmüll' },
  { item: 'Rasierklingen', bin: 'Restmüll', hint: 'Gut verpacken (Verletzungsgefahr)' },
];
